git clone https://github.com/liferay/liferay-portal.git ./liferay/liferay-portal
git clone https://github.com/aosp-mirror/platform_frameworks_base.git ./aosp-mirror/platform_frameworks_base
git clone https://github.com/CyanogenMod/android_frameworks_base.git ./CyanogenMod/android_frameworks_base
git clone https://github.com/JetBrains/intellij-community.git ./JetBrains/intellij-community
git clone https://github.com/consulo/consulo.git ./consulo/consulo
git clone https://github.com/JetBrains/MPS.git ./JetBrains/MPS
git clone https://github.com/JetBrains/kotlin.git ./JetBrains/kotlin
git clone https://github.com/nuxeo/nuxeo.git ./nuxeo/nuxeo
git clone https://github.com/openmicroscopy/openmicroscopy.git ./openmicroscopy/openmicroscopy
git clone https://github.com/apache/hadoop.git ./apache/hadoop
git clone https://github.com/xwiki/xwiki-platform.git ./xwiki/xwiki-platform
git clone https://github.com/neo4j/neo4j.git ./neo4j/neo4j
git clone https://github.com/OpenNMS/opennms.git ./OpenNMS/opennms
git clone https://github.com/apache/lucene-solr.git ./apache/lucene-solr
git clone https://github.com/elastic/elasticsearch.git ./elastic/elasticsearch
git clone https://github.com/gradle/gradle.git ./gradle/gradle
git clone https://github.com/apache/maven-plugins.git ./apache/maven-plugins
git clone https://github.com/caskdata/cdap.git ./caskdata/cdap
git clone https://github.com/sakaiproject/sakai.git ./sakaiproject/sakai
git clone https://github.com/apache/cloudstack.git ./apache/cloudstack
git clone https://github.com/osmandapp/Osmand.git ./osmandapp/Osmand
git clone https://github.com/matsim-org/matsim.git ./matsim-org/matsim
git clone https://github.com/spacewalkproject/spacewalk.git ./spacewalkproject/spacewalk
git clone https://github.com/JetBrains/android.git ./JetBrains/android
git clone https://github.com/apache/camel.git ./apache/camel
git clone https://github.com/wocommunity/wonder.git ./wocommunity/wonder
git clone https://github.com/aosp-mirror/platform_packages_apps_settings.git ./aosp-mirror/platform_packages_apps_settings
git clone https://github.com/geogebra/geogebra.git ./geogebra/geogebra
git clone https://github.com/FenixEdu/fenixedu-academic.git ./FenixEdu/fenixedu-academic
git clone https://github.com/apache/hbase.git ./apache/hbase
git clone https://github.com/liferay/liferay-plugins.git ./liferay/liferay-plugins
git clone https://github.com/eclipse/birt.git ./eclipse/birt
git clone https://github.com/javaee/glassfish.git ./javaee/glassfish
git clone https://github.com/oVirt/ovirt-engine.git ./oVirt/ovirt-engine
git clone https://github.com/apache/felix.git ./apache/felix
git clone https://github.com/aosp-mirror/platform_frameworks_support.git ./aosp-mirror/platform_frameworks_support
git clone https://github.com/apache/ambari.git ./apache/ambari
git clone https://github.com/apache/wicket.git ./apache/wicket
git clone https://github.com/apache/ofbiz.git ./apache/ofbiz
git clone https://github.com/freenet/fred.git ./freenet/fred
git clone https://github.com/sdbg/sdbg.git ./sdbg/sdbg
git clone https://github.com/mulesoft/mule.git ./mulesoft/mule
git clone https://github.com/VoltDB/voltdb.git ./VoltDB/voltdb
git clone https://github.com/strapdata/elassandra.git ./strapdata/elassandra
git clone https://github.com/magarena/magarena.git ./magarena/magarena
git clone https://github.com/rhq-project/rhq.git ./rhq-project/rhq
git clone https://github.com/wordpress-mobile/WordPress-Android.git ./wordpress-mobile/WordPress-Android
git clone https://github.com/apache/cxf.git ./apache/cxf
git clone https://github.com/geometer/FBReaderJ.git ./geometer/FBReaderJ
git clone https://github.com/eclipse/eclipse.jdt.core.git ./eclipse/eclipse.jdt.core
git clone https://github.com/apache/tomcat70.git ./apache/tomcat70
git clone https://github.com/gerrit-review/gerrit.git ./gerrit-review/gerrit
git clone https://github.com/Alluxio/alluxio.git ./Alluxio/alluxio
git clone https://github.com/eucalyptus/eucalyptus.git ./eucalyptus/eucalyptus
git clone https://github.com/deeplearning4j/deeplearning4j.git ./deeplearning4j/deeplearning4j
git clone https://github.com/processing/processing.git ./processing/processing
git clone https://github.com/apache/ignite.git ./apache/ignite
git clone https://github.com/SonarSource/sonarqube.git ./SonarSource/sonarqube
git clone https://github.com/hazelcast/hazelcast.git ./hazelcast/hazelcast
git clone https://github.com/pentaho/pentaho-kettle.git ./pentaho/pentaho-kettle
git clone https://github.com/wildfly/wildfly.git ./wildfly/wildfly
git clone https://github.com/apache/groovy.git ./apache/groovy
git clone https://github.com/zkoss/zk.git ./zkoss/zk
git clone https://github.com/h2oai/h2o-3.git ./h2oai/h2o-3
git clone https://github.com/alkacon/opencms-core.git ./alkacon/opencms-core
git clone https://github.com/apache/cassandra.git ./apache/cassandra
git clone https://github.com/languagetool-org/languagetool.git ./languagetool-org/languagetool
git clone https://github.com/openmicroscopy/bioformats.git ./openmicroscopy/bioformats
git clone https://github.com/kohsuke/jenkins.git ./kohsuke/jenkins
git clone https://github.com/findbugsproject/findbugs.git ./findbugsproject/findbugs
git clone https://github.com/broadgsa/gatk-protected.git ./broadgsa/gatk-protected
git clone https://github.com/broadgsa/gatk.git ./broadgsa/gatk
git clone https://github.com/eXist-db/exist.git ./eXist-db/exist
git clone https://github.com/typetools/checker-framework.git ./typetools/checker-framework
git clone https://github.com/graalvm/graal.git ./graalvm/graal
git clone https://github.com/rstudio/rstudio.git ./rstudio/rstudio
git clone https://github.com/orbeon/orbeon-forms.git ./orbeon/orbeon-forms
git clone https://github.com/apache/tomcat.git ./apache/tomcat
git clone https://github.com/belaban/JGroups.git ./belaban/JGroups
git clone https://github.com/SeleniumHQ/selenium.git ./SeleniumHQ/selenium
git clone https://github.com/aosp-mirror/platform_packages_apps_contacts.git ./aosp-mirror/platform_packages_apps_contacts
git clone https://github.com/apache/jackrabbit-oak.git ./apache/jackrabbit-oak
git clone https://github.com/apache/jmeter.git ./apache/jmeter
git clone https://github.com/blazegraph/database.git ./blazegraph/database
git clone https://github.com/magefree/mage.git ./magefree/mage
git clone https://github.com/vaadin/framework.git ./vaadin/framework
git clone https://github.com/enonic/xp.git ./enonic/xp
git clone https://github.com/apache/jena.git ./apache/jena
git clone https://github.com/grails/grails-core.git ./grails/grails-core
git clone https://github.com/BroadleafCommerce/BroadleafCommerce.git ./BroadleafCommerce/BroadleafCommerce
git clone https://github.com/orientechnologies/orientdb.git ./orientechnologies/orientdb
git clone https://github.com/bigbluebutton/bigbluebutton.git ./bigbluebutton/bigbluebutton
git clone https://github.com/codefollower/Cassandra-Research.git ./codefollower/Cassandra-Research
git clone https://github.com/spring-projects/spring-framework.git ./spring-projects/spring-framework
git clone https://github.com/ORCID/ORCID-Source.git ./ORCID/ORCID-Source
git clone https://github.com/apereo/cas.git ./apereo/cas
git clone https://github.com/fabric8io/fabric8.git ./fabric8io/fabric8
git clone https://github.com/kframework/k.git ./kframework/k
git clone https://github.com/Deletescape-Media/Lawnchair.git ./Deletescape-Media/Lawnchair
git clone https://github.com/Jasig/uPortal.git ./Jasig/uPortal
git clone https://github.com/usethesource/rascal.git ./usethesource/rascal
git clone https://github.com/eclipse/jetty.project.git ./eclipse/jetty.project
git clone https://github.com/apache/karaf.git ./apache/karaf
git clone https://github.com/TEAMMATES/teammates.git ./TEAMMATES/teammates
git clone https://github.com/openmrs/openmrs-core.git ./openmrs/openmrs-core
git clone https://github.com/amirzaidi/Launcher3.git ./amirzaidi/Launcher3
git clone https://github.com/liferay/liferay-docs.git ./liferay/liferay-docs
git clone https://github.com/cdk/cdk.git ./cdk/cdk
git clone https://github.com/apache/ant.git ./apache/ant
git clone https://github.com/Stratio/stratio-cassandra.git ./Stratio/stratio-cassandra
git clone https://github.com/openstreetmap/josm.git ./openstreetmap/josm
git clone https://github.com/spotbugs/spotbugs.git ./spotbugs/spotbugs
git clone https://github.com/sleuthkit/autopsy.git ./sleuthkit/autopsy
git clone https://github.com/graalvm/graal-core.git ./graalvm/graal-core
git clone https://github.com/JetBrains/intellij-plugins.git ./JetBrains/intellij-plugins
git clone https://github.com/klinker24/Android-Blur-Launcher.git ./klinker24/Android-Blur-Launcher
git clone https://github.com/stanfordnlp/CoreNLP.git ./stanfordnlp/CoreNLP
git clone https://github.com/spring-projects/spring-boot.git ./spring-projects/spring-boot
git clone https://github.com/kiegroup/drools.git ./kiegroup/drools
git clone https://github.com/apache/flink.git ./apache/flink
git clone https://github.com/HubSpot/Singularity.git ./HubSpot/Singularity
git clone https://github.com/netty/netty.git ./netty/netty
git clone https://github.com/Graylog2/graylog2-server.git ./Graylog2/graylog2-server
git clone https://github.com/EvoSuite/evosuite.git ./EvoSuite/evosuite
git clone https://github.com/bazelbuild/bazel.git ./bazelbuild/bazel
git clone https://github.com/facebook/buck.git ./facebook/buck
git clone https://github.com/yacy/yacy_search_server.git ./yacy/yacy_search_server
git clone https://github.com/libgdx/libgdx.git ./libgdx/libgdx
git clone https://github.com/infinispan/infinispan.git ./infinispan/infinispan
git clone https://github.com/hibernate/hibernate-orm.git ./hibernate/hibernate-orm
git clone https://github.com/apache/tinkerpop.git ./apache/tinkerpop
git clone https://github.com/jitsi/jitsi.git ./jitsi/jitsi
git clone https://github.com/i2p/i2p.i2p.git ./i2p/i2p.i2p
git clone https://github.com/adempiere/adempiere.git ./adempiere/adempiere
git clone https://github.com/opennetworkinglab/onos.git ./opennetworkinglab/onos
git clone https://github.com/metasfresh/metasfresh.git ./metasfresh/metasfresh
git clone https://github.com/apache/jackrabbit.git ./apache/jackrabbit
git clone https://github.com/geoserver/geoserver.git ./geoserver/geoserver
git clone https://github.com/cuba-platform/cuba.git ./cuba-platform/cuba
git clone https://github.com/apache/kylin.git ./apache/kylin
git clone https://github.com/glob3mobile/g3m.git ./glob3mobile/g3m
git clone https://github.com/apache/maven.git ./apache/maven
git clone https://github.com/vespa-engine/vespa.git ./vespa-engine/vespa
git clone https://github.com/apache/storm.git ./apache/storm
git clone https://github.com/codenvy/codenvy.git ./codenvy/codenvy
git clone https://github.com/apache/tomee.git ./apache/tomee
git clone https://github.com/freeplane/freeplane.git ./freeplane/freeplane
git clone https://github.com/JikesRVM/JikesRVM.git ./JikesRVM/JikesRVM
git clone https://github.com/pmd/pmd.git ./pmd/pmd
git clone https://github.com/prestodb/presto.git ./prestodb/presto
git clone https://github.com/jclouds/jclouds.git ./jclouds/jclouds
git clone https://github.com/apache/beam.git ./apache/beam
git clone https://github.com/jenetics/jenetics.git ./jenetics/jenetics
git clone https://github.com/JumpMind/symmetric-ds.git ./JumpMind/symmetric-ds
git clone https://github.com/eclipse/pdt.git ./eclipse/pdt
git clone https://github.com/payara/Payara.git ./payara/Payara
git clone https://github.com/keycloak/keycloak.git ./keycloak/keycloak
git clone https://github.com/apache/activemq.git ./apache/activemq
git clone https://github.com/google/closure-compiler.git ./google/closure-compiler
git clone https://github.com/LibrePlan/libreplan.git ./LibrePlan/libreplan
git clone https://github.com/apache/usergrid.git ./apache/usergrid
git clone https://github.com/Catrobat/Catroid.git ./Catrobat/Catroid
git clone https://github.com/BaseXdb/basex.git ./BaseXdb/basex
git clone https://github.com/openhab/openhab2-addons.git ./openhab/openhab2-addons
git clone https://github.com/cgeo/cgeo.git ./cgeo/cgeo
git clone https://github.com/apache/derby.git ./apache/derby
git clone https://github.com/JabRef/jabref.git ./JabRef/jabref
git clone https://github.com/Unidata/thredds.git ./Unidata/thredds
git clone https://github.com/ballerinalang/ballerina.git ./ballerinalang/ballerina
git clone https://github.com/gwtproject/gwt.git ./gwtproject/gwt
git clone https://github.com/restlet/restlet-framework-java.git ./restlet/restlet-framework-java
git clone https://github.com/DSpace/DSpace.git ./DSpace/DSpace
git clone https://github.com/camunda/camunda-bpm-platform.git ./camunda/camunda-bpm-platform
git clone https://github.com/teiid/teiid.git ./teiid/teiid
git clone https://github.com/crate/crate.git ./crate/crate
git clone https://github.com/apache/archiva.git ./apache/archiva
git clone https://github.com/IQSS/dataverse.git ./IQSS/dataverse
git clone https://github.com/nextcloud/android.git ./nextcloud/android
git clone https://github.com/spring-projects/spring-integration.git ./spring-projects/spring-integration
git clone https://github.com/Atmosphere/atmosphere.git ./Atmosphere/atmosphere
git clone https://github.com/opentripplanner/OpenTripPlanner.git ./opentripplanner/OpenTripPlanner
git clone https://github.com/pentaho/pentaho-platform.git ./pentaho/pentaho-platform
git clone https://github.com/apache/logging-log4j2.git ./apache/logging-log4j2
git clone https://github.com/graalvm/fastr.git ./graalvm/fastr
git clone https://github.com/naver/pinpoint.git ./naver/pinpoint
git clone https://github.com/weld/core.git ./weld/core
git clone https://github.com/igniterealtime/Openfire.git ./igniterealtime/Openfire
git clone https://github.com/openhab/openhab1-addons.git ./openhab/openhab1-addons
git clone https://github.com/elki-project/elki.git ./elki-project/elki
git clone https://github.com/apache/poi.git ./apache/poi
git clone https://github.com/UweTrottmann/SeriesGuide.git ./UweTrottmann/SeriesGuide
git clone https://github.com/palantir/atlasdb.git ./palantir/atlasdb
git clone https://github.com/apache/accumulo.git ./apache/accumulo
git clone https://github.com/opendaylight/controller.git ./opendaylight/controller
git clone https://github.com/geotools/geotools.git ./geotools/geotools
git clone https://github.com/checkstyle/checkstyle.git ./checkstyle/checkstyle
git clone https://github.com/k9mail/k-9.git ./k9mail/k-9
git clone https://github.com/structr/structr.git ./structr/structr
git clone https://github.com/streamsets/datacollector.git ./streamsets/datacollector
git clone https://github.com/realm/realm-java.git ./realm/realm-java
git clone https://github.com/apache/isis.git ./apache/isis
git clone https://github.com/ankidroid/Anki-Android.git ./ankidroid/Anki-Android
git clone https://github.com/druid-io/druid.git ./druid-io/druid
git clone https://github.com/actorapp/actor-platform.git ./actorapp/actor-platform
git clone https://github.com/RestComm/Restcomm-Connect.git ./RestComm/Restcomm-Connect
git clone https://github.com/aosp-mirror/platform_dalvik.git ./aosp-mirror/platform_dalvik
git clone https://github.com/flowable/flowable-engine.git ./flowable/flowable-engine
git clone https://github.com/apache/pdfbox.git ./apache/pdfbox
git clone https://github.com/hortonworks/cloudbreak.git ./hortonworks/cloudbreak
git clone https://github.com/MovingBlocks/Terasology.git ./MovingBlocks/Terasology
git clone https://github.com/UniversalMediaServer/UniversalMediaServer.git ./UniversalMediaServer/UniversalMediaServer
git clone https://github.com/javaee/grizzly.git ./javaee/grizzly
git clone https://github.com/Activiti/Activiti.git ./Activiti/Activiti
git clone https://github.com/liquibase/liquibase.git ./liquibase/liquibase
git clone https://github.com/spring-projects/spring-ide.git ./spring-projects/spring-ide
git clone https://github.com/M66B/XPrivacy.git ./M66B/XPrivacy
git clone https://github.com/perfectsense/brightspot-cms.git ./perfectsense/brightspot-cms
git clone https://github.com/errai/errai.git ./errai/errai
git clone https://github.com/kaaproject/kaa.git ./kaaproject/kaa
git clone https://github.com/fabioz/Pydev.git ./fabioz/Pydev
git clone https://github.com/apache/phoenix.git ./apache/phoenix
git clone https://github.com/robolectric/robolectric.git ./robolectric/robolectric
git clone https://github.com/BuildCraft/BuildCraft.git ./BuildCraft/BuildCraft
git clone https://github.com/MinecraftForge/MinecraftForge.git ./MinecraftForge/MinecraftForge
git clone https://github.com/codefollower/H2-Research.git ./codefollower/H2-Research
git clone https://github.com/apache/apex-malhar.git ./apache/apex-malhar
git clone https://github.com/mtotschnig/MyExpenses.git ./mtotschnig/MyExpenses
git clone https://github.com/eclipse/vert.x.git ./eclipse/vert.x
git clone https://github.com/querydsl/querydsl.git ./querydsl/querydsl
git clone https://github.com/deeplearning4j/nd4j.git ./deeplearning4j/nd4j
git clone https://github.com/erlang/erlide_eclipse.git ./erlang/erlide_eclipse
git clone https://github.com/antlr/antlr4.git ./antlr/antlr4
git clone https://github.com/owncloud/android.git ./owncloud/android
git clone https://github.com/Whiley/WhileyCompiler.git ./Whiley/WhileyCompiler
git clone https://github.com/serge-rider/dbeaver.git ./serge-rider/dbeaver
git clone https://github.com/maxcom/lorsource.git ./maxcom/lorsource
git clone https://github.com/h2database/h2database.git ./h2database/h2database
git clone https://github.com/OpenClinica/OpenClinica.git ./OpenClinica/OpenClinica
git clone https://github.com/SmartBear/soapui.git ./SmartBear/soapui
git clone https://github.com/apache/commons-math.git ./apache/commons-math
git clone https://github.com/rabbitmq/rabbitmq-java-client.git ./rabbitmq/rabbitmq-java-client
git clone https://github.com/spring-projects/spring-security.git ./spring-projects/spring-security
git clone https://github.com/Azure/azure-sdk-for-java.git ./Azure/azure-sdk-for-java
git clone https://github.com/hibernate/hibernate-search.git ./hibernate/hibernate-search
git clone https://github.com/killbill/killbill.git ./killbill/killbill
git clone https://github.com/carrot2/carrot2.git ./carrot2/carrot2
git clone https://github.com/rancher/cattle.git ./rancher/cattle
git clone https://github.com/go-lang-plugin-org/go-lang-idea-plugin.git ./go-lang-plugin-org/go-lang-idea-plugin
git clone https://github.com/kiegroup/optaplanner.git ./kiegroup/optaplanner
git clone https://github.com/jMonkeyEngine/jmonkeyengine.git ./jMonkeyEngine/jmonkeyengine
git clone https://github.com/micdoodle8/Galacticraft.git ./micdoodle8/Galacticraft
git clone https://github.com/open-keychain/open-keychain.git ./open-keychain/open-keychain
git clone https://github.com/apache/asterixdb.git ./apache/asterixdb
git clone https://github.com/datacleaner/DataCleaner.git ./datacleaner/DataCleaner
git clone https://github.com/forge/core.git ./forge/core
git clone https://github.com/spring-projects/spring-roo.git ./spring-projects/spring-roo
git clone https://github.com/zaproxy/zaproxy.git ./zaproxy/zaproxy
git clone https://github.com/real-logic/aeron.git ./real-logic/aeron
git clone https://github.com/facebook/litho.git ./facebook/litho
git clone https://github.com/mongodb/mongo-java-driver.git ./mongodb/mongo-java-driver
git clone https://github.com/pentaho/mondrian.git ./pentaho/mondrian
git clone https://github.com/lenskit/lenskit.git ./lenskit/lenskit
git clone https://github.com/bndtools/bnd.git ./bndtools/bnd
git clone https://github.com/lumifyio/lumify.git ./lumifyio/lumify
git clone https://github.com/apache/apex-core.git ./apache/apex-core
git clone https://github.com/wikimedia/apps-android-wikipedia.git ./wikimedia/apps-android-wikipedia
git clone https://github.com/tlaplus/tlaplus.git ./tlaplus/tlaplus
git clone https://github.com/xtreemfs/xtreemfs.git ./xtreemfs/xtreemfs
git clone https://github.com/onlyliuxin/coding2017.git ./onlyliuxin/coding2017
git clone https://github.com/cloudfoundry/uaa.git ./cloudfoundry/uaa
git clone https://github.com/ReactiveX/RxJava.git ./ReactiveX/RxJava
git clone https://github.com/opennars/opennars.git ./opennars/opennars
git clone https://github.com/ModeShape/modeshape.git ./ModeShape/modeshape
git clone https://github.com/junit-team/junit5.git ./junit-team/junit5
git clone https://github.com/jOOQ/jOOQ.git ./jOOQ/jOOQ
git clone https://github.com/apache/kafka.git ./apache/kafka
git clone https://github.com/dronekit/dronekit-android.git ./dronekit/dronekit-android
git clone https://github.com/igvteam/igv.git ./igvteam/igv
git clone https://github.com/resteasy/Resteasy.git ./resteasy/Resteasy
git clone https://github.com/OpenHFT/Chronicle-Engine.git ./OpenHFT/Chronicle-Engine
git clone https://github.com/kontalk/androidclient.git ./kontalk/androidclient
git clone https://github.com/apache/struts.git ./apache/struts
git clone https://github.com/SlimeKnights/TinkersConstruct.git ./SlimeKnights/TinkersConstruct
git clone https://github.com/eclipse/che.git ./eclipse/che
git clone https://github.com/kaazing/gateway.git ./kaazing/gateway
git clone https://github.com/google/guava.git ./google/guava
git clone https://github.com/jaeksoft/opensearchserver.git ./jaeksoft/opensearchserver
git clone https://github.com/DroidPlanner/Tower.git ./DroidPlanner/Tower
git clone https://github.com/zstackio/zstack.git ./zstackio/zstack
git clone https://github.com/linkedin/pinot.git ./linkedin/pinot
git clone https://github.com/spring-projects/spring-batch.git ./spring-projects/spring-batch
git clone https://github.com/biojava/biojava.git ./biojava/biojava
git clone https://github.com/Asqatasun/Asqatasun.git ./Asqatasun/Asqatasun
git clone https://github.com/Sable/soot.git ./Sable/soot
git clone https://github.com/apache/geode.git ./apache/geode
git clone https://github.com/denimgroup/threadfix.git ./denimgroup/threadfix
git clone https://github.com/nutzam/nutz.git ./nutzam/nutz
git clone https://github.com/apache/commons-lang.git ./apache/commons-lang
git clone https://github.com/Vazkii/Botania.git ./Vazkii/Botania
git clone https://github.com/RestComm/sip-servlets.git ./RestComm/sip-servlets
git clone https://github.com/gocd/gocd.git ./gocd/gocd
git clone https://github.com/wala/WALA.git ./wala/WALA
git clone https://github.com/alibaba/druid.git ./alibaba/druid
git clone https://github.com/MirakelX/mirakel-android.git ./MirakelX/mirakel-android
git clone https://github.com/forcedotcom/SalesforceMobileSDK-Android.git ./forcedotcom/SalesforceMobileSDK-Android
git clone https://github.com/ratpack/ratpack.git ./ratpack/ratpack
git clone https://github.com/jpos/jPOS.git ./jpos/jPOS
git clone https://github.com/apache/systemml.git ./apache/systemml
git clone https://github.com/unclebob/fitnesse.git ./unclebob/fitnesse
git clone https://github.com/SleepyTrousers/EnderIO.git ./SleepyTrousers/EnderIO
git clone https://github.com/eclipse/jgit.git ./eclipse/jgit
git clone https://github.com/SonarSource/sonar-java.git ./SonarSource/sonar-java
git clone https://github.com/eclipse/egit.git ./eclipse/egit
git clone https://github.com/imglib/imglib2.git ./imglib/imglib2
git clone https://github.com/Teradata/kylo.git ./Teradata/kylo
git clone https://github.com/gchq/Gaffer.git ./gchq/Gaffer
git clone https://github.com/b3log/symphony.git ./b3log/symphony
git clone https://github.com/cinchapi/concourse.git ./cinchapi/concourse
git clone https://github.com/AsyncHttpClient/async-http-client.git ./AsyncHttpClient/async-http-client
git clone https://github.com/JanusGraph/janusgraph.git ./JanusGraph/janusgraph
git clone https://github.com/f-droid/fdroidclient.git ./f-droid/fdroidclient
git clone https://github.com/Talend/tesb-rt-se.git ./Talend/tesb-rt-se
git clone https://github.com/yegor256/rultor.git ./yegor256/rultor
git clone https://github.com/twitter/heron.git ./twitter/heron
git clone https://github.com/dkpro/dkpro-core.git ./dkpro/dkpro-core
git clone https://github.com/apache/pig.git ./apache/pig
git clone https://github.com/kiegroup/droolsjbpm-integration.git ./kiegroup/droolsjbpm-integration
git clone https://github.com/rapidoid/rapidoid.git ./rapidoid/rapidoid
git clone https://github.com/dita-ot/dita-ot.git ./dita-ot/dita-ot
git clone https://github.com/iPoli/iPoli-android.git ./iPoli/iPoli-android
git clone https://github.com/drtshock/Essentials.git ./drtshock/Essentials
git clone https://github.com/timmolter/XChange.git ./timmolter/XChange
git clone https://github.com/voldemort/voldemort.git ./voldemort/voldemort
git clone https://github.com/jeremylong/DependencyCheck.git ./jeremylong/DependencyCheck
git clone https://github.com/jsettlers/settlers-remake.git ./jsettlers/settlers-remake
git clone https://github.com/mcMMO-Dev/mcMMO.git ./mcMMO-Dev/mcMMO
git clone https://github.com/airlift/airlift.git ./airlift/airlift
git clone https://github.com/codenameone/CodenameOne.git ./codenameone/CodenameOne
git clone https://github.com/wicketstuff/core.git ./wicketstuff/core
git clone https://github.com/kiegroup/jbpm.git ./kiegroup/jbpm
git clone https://github.com/thialfihar/apg.git ./thialfihar/apg
git clone https://github.com/dropwizard/dropwizard.git ./dropwizard/dropwizard
git clone https://github.com/gephi/gephi.git ./gephi/gephi
git clone https://github.com/plutext/docx4j.git ./plutext/docx4j
git clone https://github.com/apache/incubator-gobblin.git ./apache/incubator-gobblin
git clone https://github.com/mockito/mockito.git ./mockito/mockito
git clone https://github.com/aidancbrady/Mekanism.git ./aidancbrady/Mekanism
git clone https://github.com/stanfordnlp/phrasal.git ./stanfordnlp/phrasal
git clone https://github.com/apache/fineract.git ./apache/fineract
git clone https://github.com/apache/activemq-artemis.git ./apache/activemq-artemis
git clone https://github.com/jpcsp/jpcsp.git ./jpcsp/jpcsp
git clone https://github.com/ethereum/ethereumj.git ./ethereum/ethereumj
git clone https://github.com/apache/velocity-engine.git ./apache/velocity-engine
git clone https://github.com/marytts/marytts.git ./marytts/marytts
git clone https://github.com/mucommander/mucommander.git ./mucommander/mucommander
git clone https://github.com/RIPE-NCC/whois.git ./RIPE-NCC/whois
git clone https://github.com/wso2/product-is.git ./wso2/product-is
git clone https://github.com/tananaev/traccar.git ./tananaev/traccar
git clone https://github.com/FasterXML/jackson-databind.git ./FasterXML/jackson-databind
git clone https://github.com/bisq-network/exchange.git ./bisq-network/exchange
git clone https://github.com/mikera/vectorz.git ./mikera/vectorz
git clone https://github.com/apache/nifi.git ./apache/nifi
git clone https://github.com/bcgit/bc-java.git ./bcgit/bc-java
git clone https://github.com/siacs/Conversations.git ./siacs/Conversations
git clone https://github.com/eclipse/kura.git ./eclipse/kura
git clone https://github.com/broadinstitute/gatk.git ./broadinstitute/gatk
git clone https://github.com/apache/tika.git ./apache/tika
git clone https://github.com/google/ExoPlayer.git ./google/ExoPlayer
git clone https://github.com/SpongePowered/SpongeCommon.git ./SpongePowered/SpongeCommon
git clone https://github.com/itext/itextpdf.git ./itext/itextpdf
git clone https://github.com/jbehave/jbehave-core.git ./jbehave/jbehave-core
git clone https://github.com/wso2/product-apim.git ./wso2/product-apim
git clone https://github.com/ForgeEssentials/ForgeEssentials.git ./ForgeEssentials/ForgeEssentials
git clone https://github.com/chocoteam/choco-solver.git ./chocoteam/choco-solver
git clone https://github.com/apache/zeppelin.git ./apache/zeppelin
git clone https://github.com/wso2-attic/product-emm.git ./wso2-attic/product-emm
git clone https://github.com/moneymanagerex/android-money-manager-ex.git ./moneymanagerex/android-money-manager-ex
git clone https://github.com/openMF/mifosx.git ./openMF/mifosx
git clone https://github.com/vavr-io/vavr.git ./vavr-io/vavr
git clone https://github.com/usc-isi-i2/Web-Karma.git ./usc-isi-i2/Web-Karma
git clone https://github.com/stormpath/stormpath-sdk-java.git ./stormpath/stormpath-sdk-java
git clone https://github.com/raphw/byte-buddy.git ./raphw/byte-buddy
git clone https://github.com/apache/incubator-guacamole-client.git ./apache/incubator-guacamole-client
git clone https://github.com/ops4j/org.ops4j.pax.web.git ./ops4j/org.ops4j.pax.web
git clone https://github.com/glyptodon/guacamole-client.git ./glyptodon/guacamole-client
git clone https://github.com/Deadrik/TFCraft.git ./Deadrik/TFCraft
git clone https://github.com/Glitchfiend/BiomesOPlenty.git ./Glitchfiend/BiomesOPlenty
git clone https://github.com/spring-cloud/spring-cloud-netflix.git ./spring-cloud/spring-cloud-netflix
git clone https://github.com/hibernate/hibernate-validator.git ./hibernate/hibernate-validator
git clone https://github.com/AntennaPod/AntennaPod.git ./AntennaPod/AntennaPod
git clone https://github.com/owlcs/owlapi.git ./owlcs/owlapi
git clone https://github.com/apache/mahout.git ./apache/mahout
git clone https://github.com/Team-RTG/Realistic-Terrain-Generation.git ./Team-RTG/Realistic-Terrain-Generation
git clone https://github.com/arx-deidentifier/arx.git ./arx-deidentifier/arx
git clone https://github.com/OpenGamma/Strata.git ./OpenGamma/Strata
git clone https://github.com/frostwire/frostwire.git ./frostwire/frostwire
git clone https://github.com/google/j2objc.git ./google/j2objc
git clone https://github.com/impetus-opensource/Kundera.git ./impetus-opensource/Kundera
git clone https://github.com/oblac/jodd.git ./oblac/jodd
git clone https://github.com/apache/aurora.git ./apache/aurora
git clone https://github.com/protegeproject/protege.git ./protegeproject/protege
git clone https://github.com/broadinstitute/picard.git ./broadinstitute/picard
git clone https://github.com/Audiveris/audiveris.git ./Audiveris/audiveris
git clone https://github.com/groovy/groovy-eclipse.git ./groovy/groovy-eclipse
git clone https://github.com/cloudfoundry/cf-java-client.git ./cloudfoundry/cf-java-client
git clone https://github.com/zalando/nakadi.git ./zalando/nakadi
git clone https://github.com/vector-im/riot-android.git ./vector-im/riot-android
git clone https://github.com/randoop/randoop.git ./randoop/randoop
git clone https://github.com/eclipse/smarthome.git ./eclipse/smarthome
git clone https://github.com/apache/drill.git ./apache/drill
git clone https://github.com/kickstarter/android-oss.git ./kickstarter/android-oss
git clone https://github.com/apache/cordova-android.git ./apache/cordova-android
git clone https://github.com/locationtech/geowave.git ./locationtech/geowave
git clone https://github.com/datastax/java-driver.git ./datastax/java-driver
git clone https://github.com/DDT-IDE/DDT.git ./DDT-IDE/DDT
git clone https://github.com/OpenHFT/Chronicle-Queue.git ./OpenHFT/Chronicle-Queue
git clone https://github.com/daneren2005/Subsonic.git ./daneren2005/Subsonic
git clone https://github.com/caelum/vraptor4.git ./caelum/vraptor4
git clone https://github.com/opensourceBIM/BIMserver.git ./opensourceBIM/BIMserver
git clone https://github.com/griffon/griffon.git ./griffon/griffon
git clone https://github.com/google/conscrypt.git ./google/conscrypt
git clone https://github.com/aerogear/aerogear-unifiedpush-server.git ./aerogear/aerogear-unifiedpush-server
git clone https://github.com/caelum/mamute.git ./caelum/mamute
git clone https://github.com/java-native-access/jna.git ./java-native-access/jna
git clone https://github.com/pentaho/pentaho-reporting.git ./pentaho/pentaho-reporting
git clone https://github.com/WhisperSystems/Signal-Android.git ./WhisperSystems/Signal-Android
git clone https://github.com/graphhopper/graphhopper.git ./graphhopper/graphhopper
git clone https://github.com/jfree/jfreechart.git ./jfree/jfreechart
git clone https://github.com/apache/james-project.git ./apache/james-project
git clone https://github.com/bugvm/bugvm.git ./bugvm/bugvm
git clone https://github.com/ehcache/ehcache3.git ./ehcache/ehcache3
git clone https://github.com/McJty/RFTools.git ./McJty/RFTools
git clone https://github.com/square/okhttp.git ./square/okhttp
git clone https://github.com/swagger-api/swagger-core.git ./swagger-api/swagger-core
git clone https://github.com/Camelcade/Perl5-IDEA.git ./Camelcade/Perl5-IDEA
git clone https://github.com/vmware/admiral.git ./vmware/admiral
git clone https://github.com/cucumber/cucumber-jvm.git ./cucumber/cucumber-jvm
git clone https://github.com/apache/tez.git ./apache/tez
git clone https://github.com/kite-sdk/kite.git ./kite-sdk/kite
git clone https://github.com/hawkular/hawkular-metrics.git ./hawkular/hawkular-metrics
git clone https://github.com/wildfly-swarm/wildfly-swarm.git ./wildfly-swarm/wildfly-swarm
git clone https://github.com/hangum/TadpoleForDBTools.git ./hangum/TadpoleForDBTools
git clone https://github.com/yukuku/androidbible.git ./yukuku/androidbible
git clone https://github.com/bndtools/bndtools.git ./bndtools/bndtools
git clone https://github.com/estatio/estatio.git ./estatio/estatio
git clone https://github.com/nysenate/OpenLegislation.git ./nysenate/OpenLegislation
git clone https://github.com/cometd/cometd.git ./cometd/cometd
git clone https://github.com/blynkkk/blynk-server.git ./blynkkk/blynk-server
git clone https://github.com/apache/httpcomponents-client.git ./apache/httpcomponents-client
git clone https://github.com/CloudSlang/cloud-slang.git ./CloudSlang/cloud-slang
git clone https://github.com/Multibit-Legacy/multibit-hd.git ./Multibit-Legacy/multibit-hd
git clone https://github.com/zxing/zxing.git ./zxing/zxing
git clone https://github.com/bitcoinj/bitcoinj.git ./bitcoinj/bitcoinj
git clone https://github.com/ccrama/Slide.git ./ccrama/Slide
git clone https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector.git ./CellularPrivacy/Android-IMSI-Catcher-Detector
git clone https://github.com/Treeptik/cloudunit.git ./Treeptik/cloudunit
git clone https://github.com/meganz/android.git ./meganz/android
git clone https://github.com/willuhn/hibiscus.git ./willuhn/hibiscus
git clone https://github.com/redisson/redisson.git ./redisson/redisson
git clone https://github.com/tinyMediaManager/tinyMediaManager.git ./tinyMediaManager/tinyMediaManager
git clone https://github.com/novoda/spikes.git ./novoda/spikes
git clone https://github.com/puniverse/quasar.git ./puniverse/quasar
git clone https://github.com/speedment/speedment.git ./speedment/speedment
git clone https://github.com/wso2/siddhi.git ./wso2/siddhi
git clone https://github.com/AuthMe/AuthMeReloaded.git ./AuthMe/AuthMeReloaded
git clone https://github.com/apache/httpcomponents-core.git ./apache/httpcomponents-core
git clone https://github.com/mjdenham/and-bible.git ./mjdenham/and-bible
git clone https://github.com/Blood-Asp/GT5-Unofficial.git ./Blood-Asp/GT5-Unofficial
git clone https://github.com/apache/commons-collections.git ./apache/commons-collections
git clone https://github.com/spring-projects/spring-data-mongodb.git ./spring-projects/spring-data-mongodb
git clone https://github.com/asakusafw/asakusafw.git ./asakusafw/asakusafw
git clone https://github.com/jersey/jersey.git ./jersey/jersey
git clone https://github.com/AppliedEnergistics/Applied-Energistics-2.git ./AppliedEnergistics/Applied-Energistics-2
git clone https://github.com/RUB-NDS/TLS-Attacker.git ./RUB-NDS/TLS-Attacker
git clone https://github.com/pockethub/PocketHub.git ./pockethub/PocketHub
git clone https://github.com/syncany/syncany.git ./syncany/syncany
git clone https://github.com/NoCheatPlus/NoCheatPlus.git ./NoCheatPlus/NoCheatPlus
git clone https://github.com/spotify/helios.git ./spotify/helios
git clone https://github.com/igniterealtime/Smack.git ./igniterealtime/Smack
git clone https://github.com/hibernate/hibernate-ogm.git ./hibernate/hibernate-ogm
git clone https://github.com/RS485/LogisticsPipes.git ./RS485/LogisticsPipes
git clone https://github.com/itext/itext7.git ./itext/itext7
git clone https://github.com/LiveRamp/hank.git ./LiveRamp/hank
git clone https://github.com/christophd/citrus.git ./christophd/citrus
git clone https://github.com/CorfuDB/CorfuDB.git ./CorfuDB/CorfuDB
git clone https://github.com/OpenGrok/OpenGrok.git ./OpenGrok/OpenGrok
git clone https://github.com/StripesFramework/stripes.git ./StripesFramework/stripes
git clone https://github.com/jamesagnew/hapi-fhir.git ./jamesagnew/hapi-fhir
git clone https://github.com/jolie/jolie.git ./jolie/jolie
git clone https://github.com/alibaba/fastjson.git ./alibaba/fastjson
git clone https://github.com/openzipkin/zipkin.git ./openzipkin/zipkin
git clone https://github.com/javamelody/javamelody.git ./javamelody/javamelody
git clone https://github.com/openimaj/openimaj.git ./openimaj/openimaj
git clone https://github.com/couchbase/couchbase-lite-android.git ./couchbase/couchbase-lite-android
git clone https://github.com/igniterealtime/Spark.git ./igniterealtime/Spark
git clone https://github.com/bitcoin-wallet/bitcoin-wallet.git ./bitcoin-wallet/bitcoin-wallet
git clone https://github.com/validator/validator.git ./validator/validator
git clone https://github.com/glowroot/glowroot.git ./glowroot/glowroot
git clone https://github.com/apache/nutch.git ./apache/nutch
git clone https://github.com/kalessil/phpinspectionsea.git ./kalessil/phpinspectionsea
git clone https://github.com/gitblit/gitblit.git ./gitblit/gitblit
git clone https://github.com/rackerlabs/blueflood.git ./rackerlabs/blueflood
git clone https://github.com/treasure-data/digdag.git ./treasure-data/digdag
git clone https://github.com/fossasia/susi_server.git ./fossasia/susi_server
git clone https://github.com/AxonFramework/AxonFramework.git ./AxonFramework/AxonFramework
git clone https://github.com/addthis/hydra.git ./addthis/hydra
git clone https://github.com/M66B/NetGuard.git ./M66B/NetGuard
git clone https://github.com/floodlight/floodlight.git ./floodlight/floodlight
git clone https://github.com/wix/react-native-navigation.git ./wix/react-native-navigation
git clone https://github.com/Freeyourgadget/Gadgetbridge.git ./Freeyourgadget/Gadgetbridge
git clone https://github.com/google/error-prone.git ./google/error-prone
git clone https://github.com/spockframework/spock.git ./spockframework/spock
git clone https://github.com/Neamar/KISS.git ./Neamar/KISS
git clone https://github.com/nifty-gui/nifty-gui.git ./nifty-gui/nifty-gui
git clone https://github.com/x-stream/xstream.git ./x-stream/xstream
git clone https://github.com/GoogleCloudPlatform/google-cloud-java.git ./GoogleCloudPlatform/google-cloud-java
git clone https://github.com/pentaho/big-data-plugin.git ./pentaho/big-data-plugin
git clone https://github.com/eclipse/buildship.git ./eclipse/buildship
git clone https://github.com/KronicDeth/intellij-elixir.git ./KronicDeth/intellij-elixir
git clone https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server.git ./mitreid-connect/OpenID-Connect-Java-Spring-Server
git clone https://github.com/codelibs/fess.git ./codelibs/fess
git clone https://github.com/adjust/android_sdk.git ./adjust/android_sdk
git clone https://github.com/apache/bigtop.git ./apache/bigtop
git clone https://github.com/graalvm/sulong.git ./graalvm/sulong
git clone https://github.com/GoClipse/goclipse.git ./GoClipse/goclipse
git clone https://github.com/androidannotations/androidannotations.git ./androidannotations/androidannotations
git clone https://github.com/substratum/substratum.git ./substratum/substratum
git clone https://github.com/OpenHFT/Chronicle-Map.git ./OpenHFT/Chronicle-Map
git clone https://github.com/SpongePowered/SpongeForge.git ./SpongePowered/SpongeForge
git clone https://github.com/raoulvdberge/refinedstorage.git ./raoulvdberge/refinedstorage
git clone https://github.com/atomix/atomix.git ./atomix/atomix
git clone https://github.com/Adobe-Consulting-Services/acs-aem-commons.git ./Adobe-Consulting-Services/acs-aem-commons
git clone https://github.com/apache/ranger.git ./apache/ranger
git clone https://github.com/vmware/photon-controller.git ./vmware/photon-controller
git clone https://github.com/undera/jmeter-plugins.git ./undera/jmeter-plugins
git clone https://github.com/apache/maven-surefire.git ./apache/maven-surefire
git clone https://github.com/ctripcorp/apollo.git ./ctripcorp/apollo
git clone https://github.com/apache/incubator-freemarker.git ./apache/incubator-freemarker
git clone https://github.com/danfickle/openhtmltopdf.git ./danfickle/openhtmltopdf
git clone https://github.com/loklak/loklak_server.git ./loklak/loklak_server
git clone https://github.com/apache/curator.git ./apache/curator
git clone https://github.com/apiman/apiman.git ./apiman/apiman
git clone https://github.com/commons-app/apps-android-commons.git ./commons-app/apps-android-commons
git clone https://github.com/pgjdbc/pgjdbc.git ./pgjdbc/pgjdbc
git clone https://github.com/simpligility/android-maven-plugin.git ./simpligility/android-maven-plugin
git clone https://github.com/dcm4che/dcm4che.git ./dcm4che/dcm4che
git clone https://github.com/GlowstoneMC/Glowstone.git ./GlowstoneMC/Glowstone
git clone https://github.com/kelemen/netbeans-gradle-project.git ./kelemen/netbeans-gradle-project
git clone https://github.com/apache/helix.git ./apache/helix
git clone https://github.com/MyCATApache/Mycat-Server.git ./MyCATApache/Mycat-Server
git clone https://github.com/sk89q/WorldEdit.git ./sk89q/WorldEdit
git clone https://github.com/mozilla/MozStumbler.git ./mozilla/MozStumbler
git clone https://github.com/openpnp/openpnp.git ./openpnp/openpnp
git clone https://github.com/apache/zookeeper.git ./apache/zookeeper
git clone https://github.com/watson-developer-cloud/java-sdk.git ./watson-developer-cloud/java-sdk
git clone https://github.com/membrane/service-proxy.git ./membrane/service-proxy
git clone https://github.com/spring-projects/spring-data-neo4j.git ./spring-projects/spring-data-neo4j
git clone https://github.com/brettwooldridge/HikariCP.git ./brettwooldridge/HikariCP
git clone https://github.com/OpenSkywalking/skywalking.git ./OpenSkywalking/skywalking
git clone https://github.com/OneBusAway/onebusaway-application-modules.git ./OneBusAway/onebusaway-application-modules
git clone https://github.com/javaparser/javaparser.git ./javaparser/javaparser
git clone https://github.com/jqno/equalsverifier.git ./jqno/equalsverifier
git clone https://github.com/apache/oozie.git ./apache/oozie
git clone https://github.com/apache/calcite.git ./apache/calcite
git clone https://github.com/mesosphere/dcos-commons.git ./mesosphere/dcos-commons
git clone https://github.com/veraPDF/veraPDF-library.git ./veraPDF/veraPDF-library
git clone https://github.com/CitizensDev/Citizens2.git ./CitizensDev/Citizens2
git clone https://github.com/dropwizard/metrics.git ./dropwizard/metrics
git clone https://github.com/apache/opennlp.git ./apache/opennlp
git clone https://github.com/ForestryMC/ForestryMC.git ./ForestryMC/ForestryMC
git clone https://github.com/federicoiosue/Omni-Notes.git ./federicoiosue/Omni-Notes
git clone https://github.com/osmdroid/osmdroid.git ./osmdroid/osmdroid
git clone https://github.com/redsolution/xabber-android.git ./redsolution/xabber-android
git clone https://github.com/ngageoint/mrgeo.git ./ngageoint/mrgeo
git clone https://github.com/iFixit/iFixitAndroid.git ./iFixit/iFixitAndroid
git clone https://github.com/jdbi/jdbi.git ./jdbi/jdbi
git clone https://github.com/SilenceIM/Silence.git ./SilenceIM/Silence
git clone https://github.com/kotcrab/vis-editor.git ./kotcrab/vis-editor
git clone https://github.com/spring-projects/spring-data-commons.git ./spring-projects/spring-data-commons
git clone https://github.com/opendatakit/collect.git ./opendatakit/collect
git clone https://github.com/edx/edx-app-android.git ./edx/edx-app-android
git clone https://github.com/yegor256/takes.git ./yegor256/takes
git clone https://github.com/protegeproject/webprotege.git ./protegeproject/webprotege
git clone https://github.com/zendesk/maxwell.git ./zendesk/maxwell
git clone https://github.com/codeborne/selenide.git ./codeborne/selenide
git clone https://github.com/vrapper/vrapper.git ./vrapper/vrapper
git clone https://github.com/subclipse/subclipse.git ./subclipse/subclipse
git clone https://github.com/GeoWebCache/geowebcache.git ./GeoWebCache/geowebcache
git clone https://github.com/spring-io/sagan.git ./spring-io/sagan
git clone https://github.com/jcabi/jcabi-github.git ./jcabi/jcabi-github
git clone https://github.com/SpongePowered/SpongeAPI.git ./SpongePowered/SpongeAPI
git clone https://github.com/samtools/htsjdk.git ./samtools/htsjdk
git clone https://github.com/tomahawk-player/tomahawk-android.git ./tomahawk-player/tomahawk-android
git clone https://github.com/Netflix/eureka.git ./Netflix/eureka
git clone https://github.com/apache/flume.git ./apache/flume
git clone https://github.com/lucee/Lucee.git ./lucee/Lucee
git clone https://github.com/irccloud/android.git ./irccloud/android
git clone https://github.com/grpc/grpc-java.git ./grpc/grpc-java
git clone https://github.com/slapperwan/gh4a.git ./slapperwan/gh4a
git clone https://github.com/MinimallyCorrect/TickThreading.git ./MinimallyCorrect/TickThreading
git clone https://github.com/mybatis/mybatis-3.git ./mybatis/mybatis-3
git clone https://github.com/Athou/commafeed.git ./Athou/commafeed
git clone https://github.com/serso/android-calculatorpp.git ./serso/android-calculatorpp
git clone https://github.com/ebean-orm/ebean.git ./ebean-orm/ebean
git clone https://github.com/Nukkit/Nukkit.git ./Nukkit/Nukkit
git clone https://github.com/lessthanoptimal/BoofCV.git ./lessthanoptimal/BoofCV
git clone https://github.com/mysql/mysql-connector-j.git ./mysql/mysql-connector-j
git clone https://github.com/spring-cloud/spring-cloud-sleuth.git ./spring-cloud/spring-cloud-sleuth
git clone https://github.com/junit-team/junit4.git ./junit-team/junit4
git clone https://github.com/dayatang/dddlib.git ./dayatang/dddlib
git clone https://github.com/Raizlabs/DBFlow.git ./Raizlabs/DBFlow
git clone https://github.com/wireapp/wire-android.git ./wireapp/wire-android
git clone https://github.com/jankotek/mapdb.git ./jankotek/mapdb
git clone https://github.com/TeamAmaze/AmazeFileManager.git ./TeamAmaze/AmazeFileManager
git clone https://github.com/almalence/OpenCamera.git ./almalence/OpenCamera
git clone https://github.com/pac4j/pac4j.git ./pac4j/pac4j
git clone https://github.com/QuickBlox/q-municate-android.git ./QuickBlox/q-municate-android
git clone https://github.com/wso2/msf4j.git ./wso2/msf4j
git clone https://github.com/arnaudroger/SimpleFlatMapper.git ./arnaudroger/SimpleFlatMapper
git clone https://github.com/iluwatar/java-design-patterns.git ./iluwatar/java-design-patterns
git clone https://github.com/GoogleCloudPlatform/DataflowJavaSDK.git ./GoogleCloudPlatform/DataflowJavaSDK
git clone https://github.com/haiwen/seadroid.git ./haiwen/seadroid
git clone https://github.com/jMetal/jMetal.git ./jMetal/jMetal
git clone https://github.com/gdg-x/frisbee.git ./gdg-x/frisbee
git clone https://github.com/mediathekview/MediathekView.git ./mediathekview/MediathekView
git clone https://github.com/brmson/yodaqa.git ./brmson/yodaqa
git clone https://github.com/eclipse/golo-lang.git ./eclipse/golo-lang
git clone https://github.com/ReactiveX/RxNetty.git ./ReactiveX/RxNetty
git clone https://github.com/Netflix/Hystrix.git ./Netflix/Hystrix
git clone https://github.com/Awful/Awful.apk.git ./Awful/Awful.apk
git clone https://github.com/cwensel/cascading.git ./cwensel/cascading
git clone https://github.com/RaiMan/SikuliX-2014.git ./RaiMan/SikuliX-2014
git clone https://github.com/BluSunrize/ImmersiveEngineering.git ./BluSunrize/ImmersiveEngineering
git clone https://github.com/embulk/embulk.git ./embulk/embulk
git clone https://github.com/exteso/alf.io.git ./exteso/alf.io
git clone https://github.com/CogComp/cogcomp-nlp.git ./CogComp/cogcomp-nlp
git clone https://github.com/graknlabs/grakn.git ./graknlabs/grakn
git clone https://github.com/elastic/elasticsearch-hadoop.git ./elastic/elasticsearch-hadoop
git clone https://github.com/playn/playn.git ./playn/playn
git clone https://github.com/azkaban/azkaban.git ./azkaban/azkaban
git clone https://github.com/jonasoreland/runnerup.git ./jonasoreland/runnerup
git clone https://github.com/stoicflame/enunciate.git ./stoicflame/enunciate
git clone https://github.com/jitsi/libjitsi.git ./jitsi/libjitsi
git clone https://github.com/claritylab/lucida.git ./claritylab/lucida
git clone https://github.com/WayofTime/BloodMagic.git ./WayofTime/BloodMagic
git clone https://github.com/Netflix/genie.git ./Netflix/genie
git clone https://github.com/apache/parquet-mr.git ./apache/parquet-mr
git clone https://github.com/demoiselle/framework.git ./demoiselle/framework
git clone https://github.com/JFXtras/jfxtras-labs.git ./JFXtras/jfxtras-labs
git clone https://github.com/apache/commons-io.git ./apache/commons-io
git clone https://github.com/scouter-project/scouter.git ./scouter-project/scouter
git clone https://github.com/pahimar/Equivalent-Exchange-3.git ./pahimar/Equivalent-Exchange-3
git clone https://github.com/Waffle/waffle.git ./Waffle/waffle
git clone https://github.com/apache/sqoop.git ./apache/sqoop
git clone https://github.com/yusuke/twitter4j.git ./yusuke/twitter4j
git clone https://github.com/linux-china/dubbo3.git ./linux-china/dubbo3
git clone https://github.com/alibaba/dubbo.git ./alibaba/dubbo
git clone https://github.com/OneBusAway/onebusaway-android.git ./OneBusAway/onebusaway-android
git clone https://github.com/feroult/yawp.git ./feroult/yawp
git clone https://github.com/AgriCraft/AgriCraft.git ./AgriCraft/AgriCraft
git clone https://github.com/OpenMods/OpenBlocks.git ./OpenMods/OpenBlocks
git clone https://github.com/omnifaces/omnifaces.git ./omnifaces/omnifaces
git clone https://github.com/SonarSource/SonarJS.git ./SonarSource/SonarJS
git clone https://github.com/mabe02/lanterna.git ./mabe02/lanterna
git clone https://github.com/spring-projects/spring-data-redis.git ./spring-projects/spring-data-redis
git clone https://github.com/graphhopper/jsprit.git ./graphhopper/jsprit
git clone https://github.com/Slowpoke101/FTBLaunch.git ./Slowpoke101/FTBLaunch
git clone https://github.com/jitsi/jitsi-videobridge.git ./jitsi/jitsi-videobridge
git clone https://github.com/processing/processing-android.git ./processing/processing-android
git clone https://github.com/JOML-CI/JOML.git ./JOML-CI/JOML
git clone https://github.com/Rajawali/Rajawali.git ./Rajawali/Rajawali
git clone https://github.com/ninjaframework/ninja.git ./ninjaframework/ninja
git clone https://github.com/esig/dss.git ./esig/dss
git clone https://github.com/buchen/portfolio.git ./buchen/portfolio
git clone https://github.com/freedomotic/freedomotic.git ./freedomotic/freedomotic
git clone https://github.com/redpen-cc/redpen.git ./redpen-cc/redpen
git clone https://github.com/bumptech/glide.git ./bumptech/glide
git clone https://github.com/seven332/EhViewer.git ./seven332/EhViewer
git clone https://github.com/MariaDB/mariadb-connector-j.git ./MariaDB/mariadb-connector-j
git clone https://github.com/spring-cloud/spring-cloud-config.git ./spring-cloud/spring-cloud-config
git clone https://github.com/rzwitserloot/lombok.git ./rzwitserloot/lombok
git clone https://github.com/HaxeFoundation/intellij-haxe.git ./HaxeFoundation/intellij-haxe
git clone https://github.com/mit-cml/appinventor-sources.git ./mit-cml/appinventor-sources
git clone https://github.com/RustDT/RustDT.git ./RustDT/RustDT
git clone https://github.com/ignatov/intellij-erlang.git ./ignatov/intellij-erlang
git clone https://github.com/rusher81572/cloudExplorer.git ./rusher81572/cloudExplorer
git clone https://github.com/ProtocolSupport/ProtocolSupport.git ./ProtocolSupport/ProtocolSupport
git clone https://github.com/mongodb/morphia.git ./mongodb/morphia
git clone https://github.com/linkedin/ambry.git ./linkedin/ambry
git clone https://github.com/TeamNewPipe/NewPipe.git ./TeamNewPipe/NewPipe
git clone https://github.com/dreamhead/moco.git ./dreamhead/moco
git clone https://github.com/INRIA/spoon.git ./INRIA/spoon
git clone https://github.com/HabitRPG/habitica-android.git ./HabitRPG/habitica-android
git clone https://github.com/Haehnchen/idea-php-symfony2-plugin.git ./Haehnchen/idea-php-symfony2-plugin
git clone https://github.com/bodar/totallylazy.git ./bodar/totallylazy
git clone https://github.com/mapfish/mapfish-print.git ./mapfish/mapfish-print
git clone https://github.com/vanilla-music/vanilla.git ./vanilla-music/vanilla
git clone https://github.com/facebook/fresco.git ./facebook/fresco
git clone https://github.com/fabric8io/docker-maven-plugin.git ./fabric8io/docker-maven-plugin
git clone https://github.com/mikepenz/MaterialDrawer.git ./mikepenz/MaterialDrawer
git clone https://github.com/googleads/aw-reporting.git ./googleads/aw-reporting
git clone https://github.com/openxc/openxc-android.git ./openxc/openxc-android
git clone https://github.com/pravega/pravega.git ./pravega/pravega
git clone https://github.com/reactor/reactor-core.git ./reactor/reactor-core
git clone https://github.com/salesforce/Argus.git ./salesforce/Argus
git clone https://github.com/dianrong/UniAuth.git ./dianrong/UniAuth
git clone https://github.com/joel-costigliola/assertj-core.git ./joel-costigliola/assertj-core
git clone https://github.com/Railcraft/Railcraft.git ./Railcraft/Railcraft
git clone https://github.com/AzureAD/azure-activedirectory-library-for-android.git ./AzureAD/azure-activedirectory-library-for-android
git clone https://github.com/shardingjdbc/sharding-jdbc.git ./shardingjdbc/sharding-jdbc
git clone https://github.com/quran/quran_android.git ./quran/quran_android
git clone https://github.com/Stratio/cassandra-lucene-index.git ./Stratio/cassandra-lucene-index
git clone https://github.com/schildbach/public-transport-enabler.git ./schildbach/public-transport-enabler
git clone https://github.com/spring-projects/spring-data-jpa.git ./spring-projects/spring-data-jpa
git clone https://github.com/ical4j/ical4j.git ./ical4j/ical4j
git clone https://github.com/lettuce-io/lettuce-core.git ./lettuce-io/lettuce-core
git clone https://github.com/spring-cloud/spring-cloud-aws.git ./spring-cloud/spring-cloud-aws
git clone https://github.com/xetorthio/jedis.git ./xetorthio/jedis
git clone https://github.com/psi-probe/psi-probe.git ./psi-probe/psi-probe
git clone https://github.com/b3log/solo.git ./b3log/solo
git clone https://github.com/farkam135/GoIV.git ./farkam135/GoIV
git clone https://github.com/tonihele/OpenKeeper.git ./tonihele/OpenKeeper
git clone https://github.com/PhoenicisOrg/POL-POM-5.git ./PhoenicisOrg/POL-POM-5
git clone https://github.com/AlmasB/FXGL.git ./AlmasB/FXGL
git clone https://github.com/digitalfondue/lavagna.git ./digitalfondue/lavagna
git clone https://github.com/toolbox4minecraft/amidst.git ./toolbox4minecraft/amidst
git clone https://github.com/konsoletyper/teavm.git ./konsoletyper/teavm
git clone https://github.com/javers/javers.git ./javers/javers
git clone https://github.com/PhilJay/MPAndroidChart.git ./PhilJay/MPAndroidChart
git clone https://github.com/spring-projects/spring-hadoop.git ./spring-projects/spring-hadoop
git clone https://github.com/hibernate/hibernate-tools.git ./hibernate/hibernate-tools
git clone https://github.com/vmware/xenon.git ./vmware/xenon
git clone https://github.com/flyway/flyway.git ./flyway/flyway
git clone https://github.com/getsentry/sentry-java.git ./getsentry/sentry-java
git clone https://github.com/LambdaInnovation/AcademyCraft.git ./LambdaInnovation/AcademyCraft
git clone https://github.com/ddf-project/DDF.git ./ddf-project/DDF
git clone https://github.com/torakiki/sejda.git ./torakiki/sejda
git clone https://github.com/spring-projects/spring-amqp.git ./spring-projects/spring-amqp
git clone https://github.com/real-logic/simple-binary-encoding.git ./real-logic/simple-binary-encoding
git clone https://github.com/rhuss/jolokia.git ./rhuss/jolokia
git clone https://github.com/twosigma/beakerx.git ./twosigma/beakerx
git clone https://github.com/Esri/arcgis-runtime-samples-android.git ./Esri/arcgis-runtime-samples-android
git clone https://github.com/apache/incubator-hivemall.git ./apache/incubator-hivemall
git clone https://github.com/testwhat/SmaliEx.git ./testwhat/SmaliEx
git clone https://github.com/mapsforge/mapsforge.git ./mapsforge/mapsforge
git clone https://github.com/thymeleaf/thymeleaf.git ./thymeleaf/thymeleaf
git clone https://github.com/dianping/pigeon.git ./dianping/pigeon
git clone https://github.com/stagemonitor/stagemonitor.git ./stagemonitor/stagemonitor
git clone https://github.com/feixiao/DesignPattern.git ./feixiao/DesignPattern
git clone https://github.com/ushahidi/SMSSync.git ./ushahidi/SMSSync
git clone https://github.com/google/science-journal.git ./google/science-journal
git clone https://github.com/Peergos/Peergos.git ./Peergos/Peergos
git clone https://github.com/sinkillerj/ProjectE.git ./sinkillerj/ProjectE
git clone https://github.com/QuickBlox/quickblox-android-sdk.git ./QuickBlox/quickblox-android-sdk
git clone https://github.com/umlet/umlet.git ./umlet/umlet
git clone https://github.com/AOKP/packages_apps_ROMControl.git ./AOKP/packages_apps_ROMControl
git clone https://github.com/RocketChat/Rocket.Chat.Android.git ./RocketChat/Rocket.Chat.Android
git clone https://github.com/twilio/twilio-java.git ./twilio/twilio-java
git clone https://github.com/bither/bither-android.git ./bither/bither-android
git clone https://github.com/fabric8io/kubernetes-client.git ./fabric8io/kubernetes-client
git clone https://github.com/intuit/wasabi.git ./intuit/wasabi
git clone https://github.com/jMonkeyEngine/sdk.git ./jMonkeyEngine/sdk
git clone https://github.com/docker-java/docker-java.git ./docker-java/docker-java
git clone https://github.com/JesusFreke/smali.git ./JesusFreke/smali
git clone https://github.com/katharsis-project/katharsis-framework.git ./katharsis-project/katharsis-framework
git clone https://github.com/OpenTSDB/opentsdb.git ./OpenTSDB/opentsdb
git clone https://github.com/iDevicesInc/SweetBlue.git ./iDevicesInc/SweetBlue
git clone https://github.com/mixpanel/mixpanel-android.git ./mixpanel/mixpanel-android
git clone https://github.com/advantageous/qbit.git ./advantageous/qbit
git clone https://github.com/google/guice.git ./google/guice
git clone https://github.com/pwm-project/pwm.git ./pwm-project/pwm
git clone https://github.com/codinguser/gnucash-android.git ./codinguser/gnucash-android
git clone https://github.com/aimacode/aima-java.git ./aimacode/aima-java
git clone https://github.com/junkdog/artemis-odb.git ./junkdog/artemis-odb
git clone https://github.com/linkedin/rest.li.git ./linkedin/rest.li
git clone https://github.com/GwtMaterialDesign/gwt-material.git ./GwtMaterialDesign/gwt-material
git clone https://github.com/SonarSource/sonarlint-eclipse.git ./SonarSource/sonarlint-eclipse
git clone https://github.com/j-easy/easy-batch.git ./j-easy/easy-batch
git clone https://github.com/domaframework/doma.git ./domaframework/doma
git clone https://github.com/sitewhere/sitewhere.git ./sitewhere/sitewhere
git clone https://github.com/TheCoder4eu/BootsFaces-OSP.git ./TheCoder4eu/BootsFaces-OSP
git clone https://github.com/spring-projects/spring-data-rest.git ./spring-projects/spring-data-rest
git clone https://github.com/sk89q/WorldGuard.git ./sk89q/WorldGuard
git clone https://github.com/torodb/stampede.git ./torodb/stampede
git clone https://github.com/connectbot/connectbot.git ./connectbot/connectbot
git clone https://github.com/hidroh/materialistic.git ./hidroh/materialistic
git clone https://github.com/spacecowboy/NotePad.git ./spacecowboy/NotePad
git clone https://github.com/hawkular/hawkular-apm.git ./hawkular/hawkular-apm
git clone https://github.com/OpenHFT/Chronicle-Core.git ./OpenHFT/Chronicle-Core
git clone https://github.com/andstatus/andstatus.git ./andstatus/andstatus
git clone https://github.com/konklone/congress-android.git ./konklone/congress-android
git clone https://github.com/SonarSource/sonar-php.git ./SonarSource/sonar-php
git clone https://github.com/rest-assured/rest-assured.git ./rest-assured/rest-assured
git clone https://github.com/Wikidata/Wikidata-Toolkit.git ./Wikidata/Wikidata-Toolkit
git clone https://github.com/USC-CSSL/TACIT.git ./USC-CSSL/TACIT
git clone https://github.com/winder/Universal-G-Code-Sender.git ./winder/Universal-G-Code-Sender
git clone https://github.com/braintree/braintree_android.git ./braintree/braintree_android
git clone https://github.com/Frederikam/FredBoat.git ./Frederikam/FredBoat
git clone https://github.com/Electrical-Age/ElectricalAge.git ./Electrical-Age/ElectricalAge
git clone https://github.com/jamesdbloom/mockserver.git ./jamesdbloom/mockserver
git clone https://github.com/osiam/osiam.git ./osiam/osiam
git clone https://github.com/RoaringBitmap/RoaringBitmap.git ./RoaringBitmap/RoaringBitmap
git clone https://github.com/ObeoNetwork/UML-Designer.git ./ObeoNetwork/UML-Designer
git clone https://github.com/asterisk-java/asterisk-java.git ./asterisk-java/asterisk-java
git clone https://github.com/orbit/orbit.git ./orbit/orbit
git clone https://github.com/cloudant/sync-android.git ./cloudant/sync-android
git clone https://github.com/quickfix-j/quickfixj.git ./quickfix-j/quickfixj
git clone https://github.com/abixen/abixen-platform.git ./abixen/abixen-platform
git clone https://github.com/novoda/download-manager.git ./novoda/download-manager
git clone https://github.com/t-oster/VisiCut.git ./t-oster/VisiCut
git clone https://github.com/square/retrofit.git ./square/retrofit
git clone https://github.com/lukehutch/fast-classpath-scanner.git ./lukehutch/fast-classpath-scanner
git clone https://github.com/qos-ch/slf4j.git ./qos-ch/slf4j
git clone https://github.com/anthonycr/Lightning-Browser.git ./anthonycr/Lightning-Browser
git clone https://github.com/cyberfox/jbidwatcher.git ./cyberfox/jbidwatcher
git clone https://github.com/syncthing/syncthing-android.git ./syncthing/syncthing-android
git clone https://github.com/spotify/docker-client.git ./spotify/docker-client
git clone https://github.com/dashbuilder/dashbuilder.git ./dashbuilder/dashbuilder
git clone https://github.com/segmentio/analytics-android.git ./segmentio/analytics-android
git clone https://github.com/fossasia/open-event-android.git ./fossasia/open-event-android
git clone https://github.com/msgpack/msgpack-java.git ./msgpack/msgpack-java
git clone https://github.com/MarginallyClever/Makelangelo-software.git ./MarginallyClever/Makelangelo-software
git clone https://github.com/FasterXML/jackson-core.git ./FasterXML/jackson-core
git clone https://github.com/k0shk0sh/FastHub.git ./k0shk0sh/FastHub
git clone https://github.com/powermock/powermock.git ./powermock/powermock
git clone https://github.com/google/iosched.git ./google/iosched
git clone https://github.com/jooby-project/jooby.git ./jooby-project/jooby
git clone https://github.com/bluestreak01/questdb.git ./bluestreak01/questdb
git clone https://github.com/iBotPeaches/Apktool.git ./iBotPeaches/Apktool
git clone https://github.com/jhy/jsoup.git ./jhy/jsoup
git clone https://github.com/ATLauncher/ATLauncher.git ./ATLauncher/ATLauncher
git clone https://github.com/P2Pvalue/swellrt.git ./P2Pvalue/swellrt
git clone https://github.com/afollestad/material-dialogs.git ./afollestad/material-dialogs
git clone https://github.com/google/closure-templates.git ./google/closure-templates
git clone https://github.com/Sloeber/arduino-eclipse-plugin.git ./Sloeber/arduino-eclipse-plugin
git clone https://github.com/archimatetool/archi.git ./archimatetool/archi
git clone https://github.com/ContainX/openstack4j.git ./ContainX/openstack4j
git clone https://github.com/jacoco/jacoco.git ./jacoco/jacoco
git clone https://github.com/FluentLenium/FluentLenium.git ./FluentLenium/FluentLenium
git clone https://github.com/pietermartin/sqlg.git ./pietermartin/sqlg
git clone https://github.com/baomidou/mybatis-plus.git ./baomidou/mybatis-plus
git clone https://github.com/camelinaction/camelinaction2.git ./camelinaction/camelinaction2
git clone https://github.com/eclipse/californium.git ./eclipse/californium
git clone https://github.com/divolte/divolte-collector.git ./divolte/divolte-collector
git clone https://github.com/MassiveCraft/Factions.git ./MassiveCraft/Factions
git clone https://github.com/numenta/htm.java.git ./numenta/htm.java
git clone https://github.com/GoogleCloudPlatform/java-docs-samples.git ./GoogleCloudPlatform/java-docs-samples
git clone https://github.com/intel-hadoop/HiBench.git ./intel-hadoop/HiBench
git clone https://github.com/demilich1/metastone.git ./demilich1/metastone
git clone https://github.com/WPIRoboticsProjects/GRIP.git ./WPIRoboticsProjects/GRIP
git clone https://github.com/bitstadium/HockeySDK-Android.git ./bitstadium/HockeySDK-Android
git clone https://github.com/asciidocfx/AsciidocFX.git ./asciidocfx/AsciidocFX
git clone https://github.com/cache2k/cache2k.git ./cache2k/cache2k
git clone https://github.com/google/nomulus.git ./google/nomulus
git clone https://github.com/droidparts/droidparts.git ./droidparts/droidparts
git clone https://github.com/SoftInstigate/restheart.git ./SoftInstigate/restheart
git clone https://github.com/shouldit/android-proxy.git ./shouldit/android-proxy
git clone https://github.com/relayrides/pushy.git ./relayrides/pushy
git clone https://github.com/exercism/java.git ./exercism/java
git clone https://github.com/allure-framework/allure1.git ./allure-framework/allure1
git clone https://github.com/galenframework/galen.git ./galenframework/galen
git clone https://github.com/SpigotMC/BungeeCord.git ./SpigotMC/BungeeCord
git clone https://github.com/rakam-io/rakam.git ./rakam-io/rakam
git clone https://github.com/mycelium-com/wallet-android.git ./mycelium-com/wallet-android
git clone https://github.com/actframework/actframework.git ./actframework/actframework
git clone https://github.com/OpenHFT/Java-Lang.git ./OpenHFT/Java-Lang
git clone https://github.com/JetBrains/xodus.git ./JetBrains/xodus
git clone https://github.com/SeldonIO/seldon-server.git ./SeldonIO/seldon-server
git clone https://github.com/jtransc/jtransc.git ./jtransc/jtransc
git clone https://github.com/cSploit/android.git ./cSploit/android
git clone https://github.com/cyclestreets/android.git ./cyclestreets/android
git clone https://github.com/spotify/heroic.git ./spotify/heroic
git clone https://github.com/taskadapter/redmine-java-api.git ./taskadapter/redmine-java-api
git clone https://github.com/hs-web/hsweb-framework.git ./hs-web/hsweb-framework
git clone https://github.com/DV8FromTheWorld/JDA.git ./DV8FromTheWorld/JDA
git clone https://github.com/restfb/restfb.git ./restfb/restfb
git clone https://github.com/EdwardRaff/JSAT.git ./EdwardRaff/JSAT
git clone https://github.com/immutables/immutables.git ./immutables/immutables
git clone https://github.com/javalite/activejdbc.git ./javalite/activejdbc
git clone https://github.com/duckduckgo/android-search-and-stories.git ./duckduckgo/android-search-and-stories
git clone https://github.com/maskarade/Android-Orma.git ./maskarade/Android-Orma
git clone https://github.com/atomix/copycat.git ./atomix/copycat
git clone https://github.com/graphaware/neo4j-framework.git ./graphaware/neo4j-framework
git clone https://github.com/davidmoten/rxjava-extras.git ./davidmoten/rxjava-extras
git clone https://github.com/p6spy/p6spy.git ./p6spy/p6spy
git clone https://github.com/doanduyhai/Achilles.git ./doanduyhai/Achilles
git clone https://github.com/google/physical-web.git ./google/physical-web
git clone https://github.com/javaee-samples/javaee7-samples.git ./javaee-samples/javaee7-samples
git clone https://github.com/sannies/mp4parser.git ./sannies/mp4parser
git clone https://github.com/austinv11/Discord4J.git ./austinv11/Discord4J
git clone https://github.com/vert-x3/vertx-web.git ./vert-x3/vertx-web
git clone https://github.com/google/truth.git ./google/truth
git clone https://github.com/jmxtrans/jmxtrans.git ./jmxtrans/jmxtrans
git clone https://github.com/jenkinsci/gerrit-trigger-plugin.git ./jenkinsci/gerrit-trigger-plugin
git clone https://github.com/MachineMuse/MachineMusePowersuits.git ./MachineMuse/MachineMusePowersuits
git clone https://github.com/nextcloud/news-android.git ./nextcloud/news-android
git clone https://github.com/square/wire.git ./square/wire
git clone https://github.com/ShifuML/shifu.git ./ShifuML/shifu
git clone https://github.com/radargun/radargun.git ./radargun/radargun
git clone https://github.com/vmi/selenese-runner-java.git ./vmi/selenese-runner-java
git clone https://github.com/SquidPony/SquidLib.git ./SquidPony/SquidLib
git clone https://github.com/aws/aws-sdk-java.git ./aws/aws-sdk-java
git clone https://github.com/floragunncom/search-guard.git ./floragunncom/search-guard
git clone https://github.com/locationtech/geogig.git ./locationtech/geogig
git clone https://github.com/lipangit/JiaoZiVideoPlayer.git ./lipangit/JiaoZiVideoPlayer
git clone https://github.com/linkedin/WhereHows.git ./linkedin/WhereHows
git clone https://github.com/stripe/stripe-android.git ./stripe/stripe-android
git clone https://github.com/janino-compiler/janino.git ./janino-compiler/janino
git clone https://github.com/lindenb/jvarkit.git ./lindenb/jvarkit
git clone https://github.com/OryxProject/oryx.git ./OryxProject/oryx
git clone https://github.com/vitalidze/traccar-web.git ./vitalidze/traccar-web
git clone https://github.com/cflint/CFLint.git ./cflint/CFLint
git clone https://github.com/spring-projects/spring-data-cassandra.git ./spring-projects/spring-data-cassandra
git clone https://github.com/restx/restx.git ./restx/restx
git clone https://github.com/liato/android-bankdroid.git ./liato/android-bankdroid
git clone https://github.com/aadnk/ProtocolLib.git ./aadnk/ProtocolLib
git clone https://github.com/deeplearning4j/dl4j-examples.git ./deeplearning4j/dl4j-examples
git clone https://github.com/kabouzeid/Phonograph.git ./kabouzeid/Phonograph
git clone https://github.com/ctripcorp/x-pipe.git ./ctripcorp/x-pipe
git clone https://github.com/sleekbyte/tailor.git ./sleekbyte/tailor
git clone https://github.com/RuedigerMoeller/kontraktor.git ./RuedigerMoeller/kontraktor
git clone https://github.com/ukanth/afwall.git ./ukanth/afwall
git clone https://github.com/iotaledger/iri.git ./iotaledger/iri
git clone https://github.com/Grarak/KernelAdiutor.git ./Grarak/KernelAdiutor
git clone https://github.com/bladecoder/bladecoder-adventure-engine.git ./bladecoder/bladecoder-adventure-engine
git clone https://github.com/yahoo/elide.git ./yahoo/elide
git clone https://github.com/smartdevicelink/sdl_android.git ./smartdevicelink/sdl_android
git clone https://github.com/mendhak/gpslogger.git ./mendhak/gpslogger
git clone https://github.com/sevntu-checkstyle/sevntu.checkstyle.git ./sevntu-checkstyle/sevntu.checkstyle
git clone https://github.com/sanity/quickml.git ./sanity/quickml
git clone https://github.com/Kennyc1012/Opengur.git ./Kennyc1012/Opengur
git clone https://github.com/angelozerr/tern.java.git ./angelozerr/tern.java
git clone https://github.com/selendroid/selendroid.git ./selendroid/selendroid
git clone https://github.com/apache/bookkeeper.git ./apache/bookkeeper
git clone https://github.com/brianfrankcooper/YCSB.git ./brianfrankcooper/YCSB
git clone https://github.com/aol/cyclops.git ./aol/cyclops
git clone https://github.com/kermitt2/grobid.git ./kermitt2/grobid
git clone https://github.com/spring-projects/spring-security-oauth.git ./spring-projects/spring-security-oauth
git clone https://github.com/census-instrumentation/opencensus-java.git ./census-instrumentation/opencensus-java
git clone https://github.com/AppLozic/Applozic-Android-SDK.git ./AppLozic/Applozic-Android-SDK
git clone https://github.com/boyter/searchcode-server.git ./boyter/searchcode-server
git clone https://github.com/jline/jline3.git ./jline/jline3
git clone https://github.com/zulip/zulip-android.git ./zulip/zulip-android
git clone https://github.com/DigitalPebble/storm-crawler.git ./DigitalPebble/storm-crawler
git clone https://github.com/npgall/cqengine.git ./npgall/cqengine
git clone https://github.com/decebals/pippo.git ./decebals/pippo
git clone https://github.com/wmixvideo/nfe.git ./wmixvideo/nfe
git clone https://github.com/sandsmark/QuasselDroid.git ./sandsmark/QuasselDroid
git clone https://github.com/apache/mina-sshd.git ./apache/mina-sshd
git clone https://github.com/Microsoft/malmo.git ./Microsoft/malmo
git clone https://github.com/mgarin/weblaf.git ./mgarin/weblaf
git clone https://github.com/mezz/JustEnoughItems.git ./mezz/JustEnoughItems
git clone https://github.com/Netflix/servo.git ./Netflix/servo
git clone https://github.com/jboss-modules/jboss-modules.git ./jboss-modules/jboss-modules
git clone https://github.com/support-project/knowledge.git ./support-project/knowledge
git clone https://github.com/spring-cloud/spring-cloud-dataflow.git ./spring-cloud/spring-cloud-dataflow
git clone https://github.com/moonlight-stream/moonlight-android.git ./moonlight-stream/moonlight-android
git clone https://github.com/pfleidi/yaxim.git ./pfleidi/yaxim
git clone https://github.com/HoraApps/LeafPic.git ./HoraApps/LeafPic
git clone https://github.com/neo4j/neo4j-java-driver.git ./neo4j/neo4j-java-driver
git clone https://github.com/ebraminio/DroidPersianCalendar.git ./ebraminio/DroidPersianCalendar
git clone https://github.com/AEFeinstein/mtg-familiar.git ./AEFeinstein/mtg-familiar
git clone https://github.com/pubnub/java.git ./pubnub/java
git clone https://github.com/RoboBinding/RoboBinding.git ./RoboBinding/RoboBinding
git clone https://github.com/mikepenz/FastAdapter.git ./mikepenz/FastAdapter
git clone https://github.com/CeON/CERMINE.git ./CeON/CERMINE
git clone https://github.com/JetBrains/intellij-sdk-docs.git ./JetBrains/intellij-sdk-docs
git clone https://github.com/zalando/zalenium.git ./zalando/zalenium
git clone https://github.com/haifengl/smile.git ./haifengl/smile
git clone https://github.com/iSoron/uhabits.git ./iSoron/uhabits
git clone https://github.com/mplushnikov/lombok-intellij-plugin.git ./mplushnikov/lombok-intellij-plugin
git clone https://github.com/spring-cloud/spring-cloud-commons.git ./spring-cloud/spring-cloud-commons
git clone https://github.com/yahoo/omid.git ./yahoo/omid
git clone https://github.com/jphp-compiler/jphp.git ./jphp-compiler/jphp
git clone https://github.com/code4craft/webmagic.git ./code4craft/webmagic
git clone https://github.com/ContainerSolutions/minimesos.git ./ContainerSolutions/minimesos
git clone https://github.com/OpenCubicChunks/CubicChunks.git ./OpenCubicChunks/CubicChunks
git clone https://github.com/yahoo/squidb.git ./yahoo/squidb
git clone https://github.com/UnderwaterApps/overlap2d.git ./UnderwaterApps/overlap2d
git clone https://github.com/DataSketches/sketches-core.git ./DataSketches/sketches-core
git clone https://github.com/appium/java-client.git ./appium/java-client
git clone https://github.com/MinecraftForge/ForgeGradle.git ./MinecraftForge/ForgeGradle
git clone https://github.com/google/blockly-android.git ./google/blockly-android
git clone https://github.com/journeyapps/zxing-android-embedded.git ./journeyapps/zxing-android-embedded
git clone https://github.com/andsel/moquette.git ./andsel/moquette
git clone https://github.com/mongodb/mongo-hadoop.git ./mongodb/mongo-hadoop
git clone https://github.com/bartdag/py4j.git ./bartdag/py4j
git clone https://github.com/kohsuke/github-api.git ./kohsuke/github-api
git clone https://github.com/fengjiachun/Jupiter.git ./fengjiachun/Jupiter
git clone https://github.com/azagniotov/stubby4j.git ./azagniotov/stubby4j
git clone https://github.com/shuzheng/zheng.git ./shuzheng/zheng
git clone https://github.com/searchbox-io/Jest.git ./searchbox-io/Jest
git clone https://github.com/jenkinsci/ghprb-plugin.git ./jenkinsci/ghprb-plugin
git clone https://github.com/Mineshopper/carpentersblocks.git ./Mineshopper/carpentersblocks
git clone https://github.com/alexstyl/Memento-Calendar.git ./alexstyl/Memento-Calendar
git clone https://github.com/rsksmart/rskj.git ./rsksmart/rskj
git clone https://github.com/wiglenet/wigle-wifi-wardriving.git ./wiglenet/wigle-wifi-wardriving
git clone https://github.com/spring-cloud/spring-cloud-stream.git ./spring-cloud/spring-cloud-stream
git clone https://github.com/mikepenz/AboutLibraries.git ./mikepenz/AboutLibraries
git clone https://github.com/knightliao/disconf.git ./knightliao/disconf
git clone https://github.com/jenkinsci/email-ext-plugin.git ./jenkinsci/email-ext-plugin
git clone https://github.com/Glucosio/glucosio-android.git ./Glucosio/glucosio-android
git clone https://github.com/jmockit/jmockit1.git ./jmockit/jmockit1
git clone https://github.com/Bilibili/DanmakuFlameMaster.git ./Bilibili/DanmakuFlameMaster
git clone https://github.com/QuantumBadger/RedReader.git ./QuantumBadger/RedReader
git clone https://github.com/llbit/chunky.git ./llbit/chunky
git clone https://github.com/raulhaag/MiMangaNu.git ./raulhaag/MiMangaNu
git clone https://github.com/apache/samza.git ./apache/samza
git clone https://github.com/graphql-java/graphql-java.git ./graphql-java/graphql-java
git clone https://github.com/oltpbenchmark/oltpbench.git ./oltpbenchmark/oltpbench
git clone https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin.git ./sscarduzio/elasticsearch-readonlyrest-plugin
git clone https://github.com/carymrobbins/intellij-haskforce.git ./carymrobbins/intellij-haskforce
git clone https://github.com/cincheo/jsweet.git ./cincheo/jsweet
git clone https://github.com/eclipse/hono.git ./eclipse/hono
git clone https://github.com/NineWorlds/serenity-android.git ./NineWorlds/serenity-android
git clone https://github.com/wasdennnoch/AndroidN-ify.git ./wasdennnoch/AndroidN-ify
git clone https://github.com/iBase4J/iBase4J.git ./iBase4J/iBase4J
git clone https://github.com/phonegap/phonegap-plugin-push.git ./phonegap/phonegap-plugin-push
git clone https://github.com/mozilla-mobile/focus-android.git ./mozilla-mobile/focus-android
git clone https://github.com/neo4j/neo4j-ogm.git ./neo4j/neo4j-ogm
git clone https://github.com/PEXPlugins/PermissionsEx.git ./PEXPlugins/PermissionsEx
git clone https://github.com/maven-nar/nar-maven-plugin.git ./maven-nar/nar-maven-plugin
git clone https://github.com/owntracks/android.git ./owntracks/android
git clone https://github.com/Vazkii/Quark.git ./Vazkii/Quark
git clone https://github.com/sialcasa/mvvmFX.git ./sialcasa/mvvmFX
git clone https://github.com/MCTCP/TerrainControl.git ./MCTCP/TerrainControl
git clone https://github.com/wallabag/android-app.git ./wallabag/android-app
git clone https://github.com/qiscus/qiscus-sdk-android.git ./qiscus/qiscus-sdk-android
git clone https://github.com/romannurik/muzei.git ./romannurik/muzei
git clone https://github.com/javaparser/javasymbolsolver.git ./javaparser/javasymbolsolver
git clone https://github.com/amartinz/DeviceControl.git ./amartinz/DeviceControl
git clone https://github.com/xebialabs/overthere.git ./xebialabs/overthere
git clone https://github.com/ACRA/acra.git ./ACRA/acra
git clone https://github.com/farin/JCloisterZone.git ./farin/JCloisterZone
git clone https://github.com/allegro/hermes.git ./allegro/hermes
git clone https://github.com/Floens/Clover.git ./Floens/Clover
git clone https://github.com/firebase/FirebaseUI-Android.git ./firebase/FirebaseUI-Android
git clone https://github.com/gravitee-io/gravitee-gateway.git ./gravitee-io/gravitee-gateway
git clone https://github.com/apache/giraph.git ./apache/giraph
git clone https://github.com/apache/eagle.git ./apache/eagle
git clone https://github.com/kairosdb/kairosdb.git ./kairosdb/kairosdb
git clone https://github.com/joelittlejohn/jsonschema2pojo.git ./joelittlejohn/jsonschema2pojo
git clone https://github.com/Netflix/governator.git ./Netflix/governator
git clone https://github.com/haraldk/TwelveMonkeys.git ./haraldk/TwelveMonkeys
git clone https://github.com/boy0001/FastAsyncWorldedit.git ./boy0001/FastAsyncWorldedit
git clone https://github.com/floragunncom/search-guard-ssl.git ./floragunncom/search-guard-ssl
git clone https://github.com/mulesoft-labs/raml-for-jax-rs.git ./mulesoft-labs/raml-for-jax-rs
git clone https://github.com/line/armeria.git ./line/armeria
git clone https://github.com/asLody/VirtualApp.git ./asLody/VirtualApp
git clone https://github.com/rovo89/XposedInstaller.git ./rovo89/XposedInstaller
git clone https://github.com/springside/springside4.git ./springside/springside4
git clone https://github.com/devopsfolks/podam.git ./devopsfolks/podam
git clone https://github.com/fossasia/phimpme-android.git ./fossasia/phimpme-android
git clone https://github.com/apollo-rsps/apollo.git ./apollo-rsps/apollo
git clone https://github.com/MylesIsCool/ViaVersion.git ./MylesIsCool/ViaVersion
git clone https://github.com/davidmoten/rtree.git ./davidmoten/rtree
git clone https://github.com/ViDA-NYU/ache.git ./ViDA-NYU/ache
git clone https://github.com/Automattic/simplenote-android.git ./Automattic/simplenote-android
git clone https://github.com/pmwmedia/tinylog.git ./pmwmedia/tinylog
git clone https://github.com/pushtorefresh/storio.git ./pushtorefresh/storio
git clone https://github.com/square/picasso.git ./square/picasso
git clone https://github.com/swagger-api/swagger-parser.git ./swagger-api/swagger-parser
git clone https://github.com/mapstruct/mapstruct.git ./mapstruct/mapstruct
git clone https://github.com/FXMisc/RichTextFX.git ./FXMisc/RichTextFX
git clone https://github.com/Floobits/floobits-intellij.git ./Floobits/floobits-intellij
git clone https://github.com/FredJul/Flym.git ./FredJul/Flym
git clone https://github.com/ltsopensource/light-task-scheduler.git ./ltsopensource/light-task-scheduler
git clone https://github.com/nekopanda/logbook.git ./nekopanda/logbook
git clone https://github.com/johncarl81/transfuse.git ./johncarl81/transfuse
git clone https://github.com/btraceio/btrace.git ./btraceio/btrace
git clone https://github.com/cryptomator/cryptomator.git ./cryptomator/cryptomator
git clone https://github.com/airbnb/okreplay.git ./airbnb/okreplay
git clone https://github.com/real-logic/agrona.git ./real-logic/agrona
git clone https://github.com/apache/commons-imaging.git ./apache/commons-imaging
git clone https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer.git ./VREMSoftwareDevelopment/WiFiAnalyzer
git clone https://github.com/vipshop/Saturn.git ./vipshop/Saturn
git clone https://github.com/confluentinc/schema-registry.git ./confluentinc/schema-registry
git clone https://github.com/drewnoakes/metadata-extractor.git ./drewnoakes/metadata-extractor
git clone https://github.com/AltBeacon/android-beacon-library.git ./AltBeacon/android-beacon-library
git clone https://github.com/openmhealth/shimmer.git ./openmhealth/shimmer
git clone https://github.com/zxh0/classpy.git ./zxh0/classpy
git clone https://github.com/damianszczepanik/cucumber-reporting.git ./damianszczepanik/cucumber-reporting
git clone https://github.com/stripe/stripe-java.git ./stripe/stripe-java
git clone https://github.com/gearvrf/GearVRf-Demos.git ./gearvrf/GearVRf-Demos
git clone https://github.com/opensagres/xdocreport.git ./opensagres/xdocreport
git clone https://github.com/SpongePowered/SpongeVanilla.git ./SpongePowered/SpongeVanilla
git clone https://github.com/openzipkin/brave.git ./openzipkin/brave
git clone https://github.com/commonsguy/cw-omnibus.git ./commonsguy/cw-omnibus
git clone https://github.com/javaee/javamail.git ./javaee/javamail
git clone https://github.com/deeplearning4j/DataVec.git ./deeplearning4j/DataVec
git clone https://github.com/gwtbootstrap3/gwtbootstrap3.git ./gwtbootstrap3/gwtbootstrap3
git clone https://github.com/uber/okbuck.git ./uber/okbuck
git clone https://github.com/Swagger2Markup/swagger2markup.git ./Swagger2Markup/swagger2markup
git clone https://github.com/ChrisRM/material-theme-jetbrains.git ./ChrisRM/material-theme-jetbrains
